<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountriesLocalizedFrSeeder extends Seeder {

	public function run()
	{
		$query = <<<EOT
		INSERT INTO countries_localized (country_code, locale_id, name) VALUES
		('AF', 'fr', 'Afghanistan'),
		('ZA', 'fr', 'Afrique du Sud'),
		('AL', 'fr', 'Albanie'),
		('DZ', 'fr', 'Algérie'),
		('DE', 'fr', 'Allemagne'),
		('AD', 'fr', 'Andorre'),
		('AO', 'fr', 'Angola'),
		('AI', 'fr', 'Anguilla'),
		('AQ', 'fr', 'Antarctique'),
		('AG', 'fr', 'Antigua-et-Barbuda'),
		('AN', 'fr', 'Antilles néerlandaises'),
		('SA', 'fr', 'Arabie saoudite'),
		('AR', 'fr', 'Argentine'),
		('AM', 'fr', 'Arménie'),
		('AW', 'fr', 'Aruba'),
		('AU', 'fr', 'Australie'),
		('AT', 'fr', 'Autriche'),
		('AZ', 'fr', 'Azerbaïdjan'),
		('BS', 'fr', 'Bahamas'),
		('BH', 'fr', 'Bahreïn'),
		('BD', 'fr', 'Bangladesh'),
		('BB', 'fr', 'Barbade'),
		('BE', 'fr', 'Belgique'),
		('BZ', 'fr', 'Belize'),
		('BM', 'fr', 'Bermudes'),
		('BT', 'fr', 'Bhoutan'),
		('BO', 'fr', 'Bolivie'),
		('BA', 'fr', 'Bosnie-Herzégovine'),
		('BW', 'fr', 'Botswana'),
		('BN', 'fr', 'Brunéi Darussalam'),
		('BR', 'fr', 'Brésil'),
		('BG', 'fr', 'Bulgarie'),
		('BF', 'fr', 'Burkina Faso'),
		('BI', 'fr', 'Burundi'),
		('BY', 'fr', 'Bélarus'),
		('BJ', 'fr', 'Bénin'),
		('KH', 'fr', 'Cambodge'),
		('CM', 'fr', 'Cameroun'),
		('CA', 'fr', 'Canada'),
		('CV', 'fr', 'Cap-Vert'),
		('CL', 'fr', 'Chili'),
		('CN', 'fr', 'Chine'),
		('CY', 'fr', 'Chypre'),
		('CO', 'fr', 'Colombie'),
		('KM', 'fr', 'Comores'),
		('CG', 'fr', 'Congo'),
		('KP', 'fr', 'Corée du Nord'),
		('KR', 'fr', 'Corée du Sud'),
		('CR', 'fr', 'Costa Rica'),
		('HR', 'fr', 'Croatie'),
		('CU', 'fr', 'Cuba'),
		('CI', 'fr', 'Côte d’Ivoire'),
		('DK', 'fr', 'Danemark'),
		('DJ', 'fr', 'Djibouti'),
		('DM', 'fr', 'Dominique'),
		('SV', 'fr', 'El Salvador'),
		('ES', 'fr', 'Espagne'),
		('EE', 'fr', 'Estonie'),
		('FJ', 'fr', 'Fidji'),
		('FI', 'fr', 'Finlande'),
		('FR', 'fr', 'France'),
		('GA', 'fr', 'Gabon'),
		('GM', 'fr', 'Gambie'),
		('GH', 'fr', 'Ghana'),
		('GI', 'fr', 'Gibraltar'),
		('GD', 'fr', 'Grenade'),
		('GL', 'fr', 'Groenland'),
		('GR', 'fr', 'Grèce'),
		('GP', 'fr', 'Guadeloupe'),
		('GU', 'fr', 'Guam'),
		('GT', 'fr', 'Guatemala'),
		('GG', 'fr', 'Guernesey'),
		('GN', 'fr', 'Guinée'),
		('GQ', 'fr', 'Guinée équatoriale'),
		('GW', 'fr', 'Guinée-Bissau'),
		('GY', 'fr', 'Guyana'),
		('GF', 'fr', 'Guyane française'),
		('GE', 'fr', 'Géorgie'),
		('GS', 'fr', 'Géorgie du Sud et les îles Sandwich du Sud'),
		('HT', 'fr', 'Haïti'),
		('HN', 'fr', 'Honduras'),
		('HU', 'fr', 'Hongrie'),
		('IN', 'fr', 'Inde'),
		('ID', 'fr', 'Indonésie'),
		('IQ', 'fr', 'Irak'),
		('IR', 'fr', 'Iran'),
		('IE', 'fr', 'Irlande'),
		('IS', 'fr', 'Islande'),
		('IL', 'fr', 'Israël'),
		('IT', 'fr', 'Italie'),
		('JM', 'fr', 'Jamaïque'),
		('JP', 'fr', 'Japon'),
		('JE', 'fr', 'Jersey'),
		('JO', 'fr', 'Jordanie'),
		('KZ', 'fr', 'Kazakhstan'),
		('KE', 'fr', 'Kenya'),
		('KG', 'fr', 'Kirghizistan'),
		('KI', 'fr', 'Kiribati'),
		('KW', 'fr', 'Koweït'),
		('LA', 'fr', 'Laos'),
		('LS', 'fr', 'Lesotho'),
		('LV', 'fr', 'Lettonie'),
		('LB', 'fr', 'Liban'),
		('LY', 'fr', 'Libye'),
		('LR', 'fr', 'Libéria'),
		('LI', 'fr', 'Liechtenstein'),
		('LT', 'fr', 'Lituanie'),
		('LU', 'fr', 'Luxembourg'),
		('MK', 'fr', 'Macédoine'),
		('MG', 'fr', 'Madagascar'),
		('MY', 'fr', 'Malaisie'),
		('MW', 'fr', 'Malawi'),
		('MV', 'fr', 'Maldives'),
		('ML', 'fr', 'Mali'),
		('MT', 'fr', 'Malte'),
		('MA', 'fr', 'Maroc'),
		('MQ', 'fr', 'Martinique'),
		('MU', 'fr', 'Maurice'),
		('MR', 'fr', 'Mauritanie'),
		('YT', 'fr', 'Mayotte'),
		('MX', 'fr', 'Mexique'),
		('MD', 'fr', 'Moldavie'),
		('MC', 'fr', 'Monaco'),
		('MN', 'fr', 'Mongolie'),
		('MS', 'fr', 'Montserrat'),
		('ME', 'fr', 'Monténégro'),
		('MZ', 'fr', 'Mozambique'),
		('MM', 'fr', 'Myanmar'),
		('NA', 'fr', 'Namibie'),
		('NR', 'fr', 'Nauru'),
		('NI', 'fr', 'Nicaragua'),
		('NE', 'fr', 'Niger'),
		('NG', 'fr', 'Nigéria'),
		('NU', 'fr', 'Niue'),
		('NO', 'fr', 'Norvège'),
		('NC', 'fr', 'Nouvelle-Calédonie'),
		('NZ', 'fr', 'Nouvelle-Zélande'),
		('NP', 'fr', 'Népal'),
		('OM', 'fr', 'Oman'),
		('UG', 'fr', 'Ouganda'),
		('UZ', 'fr', 'Ouzbékistan'),
		('PK', 'fr', 'Pakistan'),
		('PW', 'fr', 'Palaos'),
		('PA', 'fr', 'Panama'),
		('PG', 'fr', 'Papouasie-Nouvelle-Guinée'),
		('PY', 'fr', 'Paraguay'),
		('NL', 'fr', 'Pays-Bas'),
		('PH', 'fr', 'Philippines'),
		('PN', 'fr', 'Pitcairn'),
		('PL', 'fr', 'Pologne'),
		('PF', 'fr', 'Polynésie française'),
		('PR', 'fr', 'Porto Rico'),
		('PT', 'fr', 'Portugal'),
		('PE', 'fr', 'Pérou'),
		('QA', 'fr', 'Qatar'),
		('HK', 'fr', 'R.A.S. chinoise de Hong Kong'),
		('MO', 'fr', 'R.A.S. chinoise de Macao'),
		('RO', 'fr', 'Roumanie'),
		('GB', 'fr', 'Royaume-Uni'),
		('RU', 'fr', 'Russie'),
		('RW', 'fr', 'Rwanda'),
		('CF', 'fr', 'République centrafricaine'),
		('DO', 'fr', 'République dominicaine'),
		('CD', 'fr', 'République démocratique du Congo'),
		('CZ', 'fr', 'République tchèque'),
		('RE', 'fr', 'Réunion'),
		('EH', 'fr', 'Sahara occidental'),
		('BL', 'fr', 'Saint-Barthélémy'),
		('KN', 'fr', 'Saint-Kitts-et-Nevis'),
		('SM', 'fr', 'Saint-Marin'),
		('MF', 'fr', 'Saint-Martin'),
		('PM', 'fr', 'Saint-Pierre-et-Miquelon'),
		('VC', 'fr', 'Saint-Vincent-et-les Grenadines'),
		('SH', 'fr', 'Sainte-Hélène'),
		('LC', 'fr', 'Sainte-Lucie'),
		('WS', 'fr', 'Samoa'),
		('AS', 'fr', 'Samoa américaines'),
		('ST', 'fr', 'Sao Tomé-et-Principe'),
		('RS', 'fr', 'Serbie'),
		('CS', 'fr', 'Serbie-et-Monténégro'),
		('SC', 'fr', 'Seychelles'),
		('SL', 'fr', 'Sierra Leone'),
		('SG', 'fr', 'Singapour'),
		('SK', 'fr', 'Slovaquie'),
		('SI', 'fr', 'Slovénie'),
		('SO', 'fr', 'Somalie'),
		('SD', 'fr', 'Soudan'),
		('LK', 'fr', 'Sri Lanka'),
		('CH', 'fr', 'Suisse'),
		('SR', 'fr', 'Suriname'),
		('SE', 'fr', 'Suède'),
		('SJ', 'fr', 'Svalbard et Île Jan Mayen'),
		('SZ', 'fr', 'Swaziland'),
		('SY', 'fr', 'Syrie'),
		('SN', 'fr', 'Sénégal'),
		('TJ', 'fr', 'Tadjikistan'),
		('TZ', 'fr', 'Tanzanie'),
		('TW', 'fr', 'Taïwan'),
		('TD', 'fr', 'Tchad'),
		('TF', 'fr', 'Terres australes françaises'),
		('IO', 'fr', "Territoire britannique de l'océan Indien"),
		('PS', 'fr', 'Territoire palestinien'),
		('TH', 'fr', 'Thaïlande'),
		('TL', 'fr', 'Timor oriental'),
		('TG', 'fr', 'Togo'),
		('TK', 'fr', 'Tokelau'),
		('TO', 'fr', 'Tonga'),
		('TT', 'fr', 'Trinité-et-Tobago'),
		('TN', 'fr', 'Tunisie'),
		('TM', 'fr', 'Turkménistan'),
		('TR', 'fr', 'Turquie'),
		('TV', 'fr', 'Tuvalu'),
		('UA', 'fr', 'Ukraine'),
		('UY', 'fr', 'Uruguay'),
		('VU', 'fr', 'Vanuatu'),
		('VE', 'fr', 'Venezuela'),
		('VN', 'fr', 'Viêt Nam'),
		('WF', 'fr', 'Wallis-et-Futuna'),
		('YE', 'fr', 'Yémen'),
		('ZM', 'fr', 'Zambie'),
		('ZW', 'fr', 'Zimbabwe'),
		('ZZ', 'fr', 'région indéterminée'),
		('EG', 'fr', 'Égypte'),
		('AE', 'fr', 'Émirats arabes unis'),
		('EC', 'fr', 'Équateur'),
		('ER', 'fr', 'Érythrée'),
		('VA', 'fr', 'État de la Cité du Vatican'),
		('FM', 'fr', 'États fédérés de Micronésie'),
		('US', 'fr', 'États-Unis'),
		('ET', 'fr', 'Éthiopie'),
		('BV', 'fr', 'Île Bouvet'),
		('CX', 'fr', 'Île Christmas'),
		('NF', 'fr', 'Île Norfolk'),
		('IM', 'fr', 'Île de Man'),
		('KY', 'fr', 'Îles Caïmans'),
		('CC', 'fr', 'Îles Cocos - Keeling'),
		('CK', 'fr', 'Îles Cook'),
		('FO', 'fr', 'Îles Féroé'),
		('HM', 'fr', 'Îles Heard et MacDonald'),
		('FK', 'fr', 'Îles Malouines'),
		('MP', 'fr', 'Îles Mariannes du Nord'),
		('MH', 'fr', 'Îles Marshall'),
		('UM', 'fr', 'Îles Mineures Éloignées des États-Unis'),
		('SB', 'fr', 'Îles Salomon'),
		('TC', 'fr', 'Îles Turks et Caïques'),
		('VG', 'fr', 'Îles Vierges britanniques'),
		('VI', 'fr', 'Îles Vierges des États-Unis'),
		('AX', 'fr', 'Îles Åland')
EOT;
		// No indentation before ending Heredoc

		DB::statement($query);
	}
}
