<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountriesLocalizedDeSeeder extends Seeder {

	public function run()
	{
		$query = <<<EOT
		INSERT INTO countries_localized (country_code, locale_id, name) VALUES
		('AF', 'de', 'Afghanistan'),
		('AX', 'de', 'Alandinseln'),
		('AL', 'de', 'Albanien'),
		('DZ', 'de', 'Algerien'),
		('UM', 'de', 'Amerikanisch-Ozeanien'),
		('AS', 'de', 'Amerikanisch-Samoa'),
		('VI', 'de', 'Amerikanische Jungferninseln'),
		('AD', 'de', 'Andorra'),
		('AO', 'de', 'Angola'),
		('AI', 'de', 'Anguilla'),
		('AQ', 'de', 'Antarktis'),
		('AG', 'de', 'Antigua und Barbuda'),
		('AR', 'de', 'Argentinien'),
		('AM', 'de', 'Armenien'),
		('AW', 'de', 'Aruba'),
		('AZ', 'de', 'Aserbaidschan'),
		('AU', 'de', 'Australien'),
		('BS', 'de', 'Bahamas'),
		('BH', 'de', 'Bahrain'),
		('BD', 'de', 'Bangladesch'),
		('BB', 'de', 'Barbados'),
		('BY', 'de', 'Belarus'),
		('BE', 'de', 'Belgien'),
		('BZ', 'de', 'Belize'),
		('BJ', 'de', 'Benin'),
		('BM', 'de', 'Bermuda'),
		('BT', 'de', 'Bhutan'),
		('BO', 'de', 'Bolivien'),
		('BA', 'de', 'Bosnien und Herzegowina'),
		('BW', 'de', 'Botsuana'),
		('BV', 'de', 'Bouvetinsel'),
		('BR', 'de', 'Brasilien'),
		('VG', 'de', 'Britische Jungferninseln'),
		('IO', 'de', 'Britisches Territorium im Indischen Ozean'),
		('BN', 'de', 'Brunei Darussalam'),
		('BG', 'de', 'Bulgarien'),
		('BF', 'de', 'Burkina Faso'),
		('BI', 'de', 'Burundi'),
		('CL', 'de', 'Chile'),
		('CN', 'de', 'China'),
		('CK', 'de', 'Cookinseln'),
		('CR', 'de', 'Costa Rica'),
		('CI', 'de', 'Côte d’Ivoire'),
		('CD', 'de', 'Demokratische Republik Kongo'),
		('KP', 'de', 'Demokratische Volksrepublik Korea'),
		('DE', 'de', 'Deutschland'),
		('DM', 'de', 'Dominica'),
		('DO', 'de', 'Dominikanische Republik'),
		('DJ', 'de', 'Dschibuti'),
		('DK', 'de', 'Dänemark'),
		('EC', 'de', 'Ecuador'),
		('SV', 'de', 'El Salvador'),
		('ER', 'de', 'Eritrea'),
		('EE', 'de', 'Estland'),
		('FK', 'de', 'Falklandinseln'),
		('FJ', 'de', 'Fidschi'),
		('FI', 'de', 'Finnland'),
		('FR', 'de', 'Frankreich'),
		('GF', 'de', 'Französisch-Guayana'),
		('PF', 'de', 'Französisch-Polynesien'),
		('TF', 'de', 'Französische Süd- und Antarktisgebiete'),
		('FO', 'de', 'Färöer'),
		('GA', 'de', 'Gabun'),
		('GM', 'de', 'Gambia'),
		('GE', 'de', 'Georgien'),
		('GH', 'de', 'Ghana'),
		('GI', 'de', 'Gibraltar'),
		('GD', 'de', 'Grenada'),
		('GR', 'de', 'Griechenland'),
		('GL', 'de', 'Grönland'),
		('GP', 'de', 'Guadeloupe'),
		('GU', 'de', 'Guam'),
		('GT', 'de', 'Guatemala'),
		('GG', 'de', 'Guernsey'),
		('GN', 'de', 'Guinea'),
		('GW', 'de', 'Guinea-Bissau'),
		('GY', 'de', 'Guyana'),
		('HT', 'de', 'Haiti'),
		('HM', 'de', 'Heard- und McDonald-Inseln'),
		('HN', 'de', 'Honduras'),
		('IN', 'de', 'Indien'),
		('ID', 'de', 'Indonesien'),
		('IQ', 'de', 'Irak'),
		('IR', 'de', 'Iran'),
		('IE', 'de', 'Irland'),
		('IS', 'de', 'Island'),
		('IM', 'de', 'Isle of Man'),
		('IL', 'de', 'Israel'),
		('IT', 'de', 'Italien'),
		('JM', 'de', 'Jamaika'),
		('JP', 'de', 'Japan'),
		('YE', 'de', 'Jemen'),
		('JE', 'de', 'Jersey'),
		('JO', 'de', 'Jordanien'),
		('KY', 'de', 'Kaimaninseln'),
		('KH', 'de', 'Kambodscha'),
		('CM', 'de', 'Kamerun'),
		('CA', 'de', 'Kanada'),
		('CV', 'de', 'Kap Verde'),
		('KZ', 'de', 'Kasachstan'),
		('QA', 'de', 'Katar'),
		('KE', 'de', 'Kenia'),
		('KG', 'de', 'Kirgisistan'),
		('KI', 'de', 'Kiribati'),
		('CC', 'de', 'Kokosinseln'),
		('CO', 'de', 'Kolumbien'),
		('KM', 'de', 'Komoren'),
		('CG', 'de', 'Kongo'),
		('HR', 'de', 'Kroatien'),
		('CU', 'de', 'Kuba'),
		('KW', 'de', 'Kuwait'),
		('LA', 'de', 'Laos'),
		('LS', 'de', 'Lesotho'),
		('LV', 'de', 'Lettland'),
		('LB', 'de', 'Libanon'),
		('LR', 'de', 'Liberia'),
		('LY', 'de', 'Libyen'),
		('LI', 'de', 'Liechtenstein'),
		('LT', 'de', 'Litauen'),
		('LU', 'de', 'Luxemburg'),
		('MG', 'de', 'Madagaskar'),
		('MW', 'de', 'Malawi'),
		('MY', 'de', 'Malaysia'),
		('MV', 'de', 'Malediven'),
		('ML', 'de', 'Mali'),
		('MT', 'de', 'Malta'),
		('MA', 'de', 'Marokko'),
		('MH', 'de', 'Marshallinseln'),
		('MQ', 'de', 'Martinique'),
		('MR', 'de', 'Mauretanien'),
		('MU', 'de', 'Mauritius'),
		('YT', 'de', 'Mayotte'),
		('MK', 'de', 'Mazedonien'),
		('MX', 'de', 'Mexiko'),
		('FM', 'de', 'Mikronesien'),
		('MC', 'de', 'Monaco'),
		('MN', 'de', 'Mongolei'),
		('ME', 'de', 'Montenegro'),
		('MS', 'de', 'Montserrat'),
		('MZ', 'de', 'Mosambik'),
		('MM', 'de', 'Myanmar'),
		('NA', 'de', 'Namibia'),
		('NR', 'de', 'Nauru'),
		('NP', 'de', 'Nepal'),
		('NC', 'de', 'Neukaledonien'),
		('NZ', 'de', 'Neuseeland'),
		('NI', 'de', 'Nicaragua'),
		('NL', 'de', 'Niederlande'),
		('AN', 'de', 'Niederländische Antillen'),
		('NE', 'de', 'Niger'),
		('NG', 'de', 'Nigeria'),
		('NU', 'de', 'Niue'),
		('NF', 'de', 'Norfolkinsel'),
		('NO', 'de', 'Norwegen'),
		('MP', 'de', 'Nördliche Marianen'),
		('OM', 'de', 'Oman'),
		('TL', 'de', 'Osttimor'),
		('PK', 'de', 'Pakistan'),
		('PW', 'de', 'Palau'),
		('PS', 'de', 'Palästinensische Gebiete'),
		('PA', 'de', 'Panama'),
		('PG', 'de', 'Papua-Neuguinea'),
		('PY', 'de', 'Paraguay'),
		('PE', 'de', 'Peru'),
		('PH', 'de', 'Philippinen'),
		('PN', 'de', 'Pitcairn'),
		('PL', 'de', 'Polen'),
		('PT', 'de', 'Portugal'),
		('PR', 'de', 'Puerto Rico'),
		('KR', 'de', 'Republik Korea'),
		('MD', 'de', 'Republik Moldau'),
		('RW', 'de', 'Ruanda'),
		('RO', 'de', 'Rumänien'),
		('RU', 'de', 'Russische Föderation'),
		('RE', 'de', 'Réunion'),
		('SB', 'de', 'Salomonen'),
		('ZM', 'de', 'Sambia'),
		('WS', 'de', 'Samoa'),
		('SM', 'de', 'San Marino'),
		('SA', 'de', 'Saudi-Arabien'),
		('SE', 'de', 'Schweden'),
		('CH', 'de', 'Schweiz'),
		('SN', 'de', 'Senegal'),
		('RS', 'de', 'Serbien'),
		('CS', 'de', 'Serbien und Montenegro'),
		('SC', 'de', 'Seychellen'),
		('SL', 'de', 'Sierra Leone'),
		('ZW', 'de', 'Simbabwe'),
		('SG', 'de', 'Singapur'),
		('SK', 'de', 'Slowakei'),
		('SI', 'de', 'Slowenien'),
		('SO', 'de', 'Somalia'),
		('HK', 'de', 'Sonderverwaltungszone Hongkong'),
		('MO', 'de', 'Sonderverwaltungszone Macao'),
		('ES', 'de', 'Spanien'),
		('LK', 'de', 'Sri Lanka'),
		('BL', 'de', 'St. Barthélemy'),
		('SH', 'de', 'St. Helena'),
		('KN', 'de', 'St. Kitts und Nevis'),
		('LC', 'de', 'St. Lucia'),
		('MF', 'de', 'St. Martin'),
		('PM', 'de', 'St. Pierre und Miquelon'),
		('VC', 'de', 'St. Vincent und die Grenadinen'),
		('SD', 'de', 'Sudan'),
		('SR', 'de', 'Suriname'),
		('SJ', 'de', 'Svalbard und Jan Mayen'),
		('SZ', 'de', 'Swasiland'),
		('SY', 'de', 'Syrien'),
		('ST', 'de', 'São Tomé und Príncipe'),
		('ZA', 'de', 'Südafrika'),
		('GS', 'de', 'Südgeorgien und die Südlichen Sandwichinseln'),
		('TJ', 'de', 'Tadschikistan'),
		('TW', 'de', 'Taiwan'),
		('TZ', 'de', 'Tansania'),
		('TH', 'de', 'Thailand'),
		('TG', 'de', 'Togo'),
		('TK', 'de', 'Tokelau'),
		('TO', 'de', 'Tonga'),
		('TT', 'de', 'Trinidad und Tobago'),
		('TD', 'de', 'Tschad'),
		('CZ', 'de', 'Tschechische Republik'),
		('TN', 'de', 'Tunesien'),
		('TM', 'de', 'Turkmenistan'),
		('TC', 'de', 'Turks- und Caicosinseln'),
		('TV', 'de', 'Tuvalu'),
		('TR', 'de', 'Türkei'),
		('UG', 'de', 'Uganda'),
		('UA', 'de', 'Ukraine'),
		('ZZ', 'de', 'Unbekannte oder ungültige Region'),
		('HU', 'de', 'Ungarn'),
		('UY', 'de', 'Uruguay'),
		('UZ', 'de', 'Usbekistan'),
		('VU', 'de', 'Vanuatu'),
		('VA', 'de', 'Vatikanstadt'),
		('VE', 'de', 'Venezuela'),
		('AE', 'de', 'Vereinigte Arabische Emirate'),
		('US', 'de', 'Vereinigte Staaten'),
		('GB', 'de', 'Vereinigtes Königreich'),
		('VN', 'de', 'Vietnam'),
		('WF', 'de', 'Wallis und Futuna'),
		('CX', 'de', 'Weihnachtsinsel'),
		('EH', 'de', 'Westsahara'),
		('CF', 'de', 'Zentralafrikanische Republik'),
		('CY', 'de', 'Zypern'),
		('EG', 'de', 'Ägypten'),
		('GQ', 'de', 'Äquatorialguinea'),
		('ET', 'de', 'Äthiopien'),
		('AT', 'de', 'Österreich')
EOT;
		// No indentation before ending Heredoc

		DB::statement($query);
	}
}
