
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AF', 'en', 'Afghanistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AL', 'en', 'Albania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DZ', 'en', 'Algeria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AS', 'en', 'American Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AD', 'en', 'Andorra');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AO', 'en', 'Angola');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AI', 'en', 'Anguilla');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AQ', 'en', 'Antarctica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AG', 'en', 'Antigua and Barbuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AR', 'en', 'Argentina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AM', 'en', 'Armenia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AW', 'en', 'Aruba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AU', 'en', 'Australia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AT', 'en', 'Austria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AZ', 'en', 'Azerbaijan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BS', 'en', 'Bahamas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BH', 'en', 'Bahrain');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BD', 'en', 'Bangladesh');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BB', 'en', 'Barbados');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BY', 'en', 'Belarus');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BE', 'en', 'Belgium');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BZ', 'en', 'Belize');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BJ', 'en', 'Benin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BM', 'en', 'Bermuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BT', 'en', 'Bhutan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BO', 'en', 'Bolivia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BA', 'en', 'Bosnia and Herzegovina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BW', 'en', 'Botswana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BV', 'en', 'Bouvet Island');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BR', 'en', 'Brazil');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BQ', 'en', 'British Antarctic Territory');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IO', 'en', 'British Indian Ocean Territory');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VG', 'en', 'British Virgin Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BN', 'en', 'Brunei');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BG', 'en', 'Bulgaria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BF', 'en', 'Burkina Faso');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BI', 'en', 'Burundi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KH', 'en', 'Cambodia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CM', 'en', 'Cameroon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CA', 'en', 'Canada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CT', 'en', 'Canton and Enderbury Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CV', 'en', 'Cape Verde');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KY', 'en', 'Cayman Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CF', 'en', 'Central African Republic');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TD', 'en', 'Chad');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CL', 'en', 'Chile');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CN', 'en', 'China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CX', 'en', 'Christmas Island');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CC', 'en', 'Cocos [Keeling] Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CO', 'en', 'Colombia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KM', 'en', 'Comoros');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CG', 'en', 'Congo - Brazzaville');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CD', 'en', 'Congo - Kinshasa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CK', 'en', 'Cook Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CR', 'en', 'Costa Rica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HR', 'en', 'Croatia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CU', 'en', 'Cuba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CY', 'en', 'Cyprus');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CZ', 'en', 'Czech Republic');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CI', 'en', 'Côte d’Ivoire');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DK', 'en', 'Denmark');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DJ', 'en', 'Djibouti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DM', 'en', 'Dominica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DO', 'en', 'Dominican Republic');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NQ', 'en', 'Dronning Maud Land');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DD', 'en', 'East Germany');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EC', 'en', 'Ecuador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EG', 'en', 'Egypt');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SV', 'en', 'El Salvador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GQ', 'en', 'Equatorial Guinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ER', 'en', 'Eritrea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EE', 'en', 'Estonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ET', 'en', 'Ethiopia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FK', 'en', 'Falkland Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FO', 'en', 'Faroe Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FJ', 'en', 'Fiji');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FI', 'en', 'Finland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FR', 'en', 'France');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GF', 'en', 'French Guiana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PF', 'en', 'French Polynesia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TF', 'en', 'French Southern Territories');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FQ', 'en', 'French Southern and Antarctic Territories');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GA', 'en', 'Gabon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GM', 'en', 'Gambia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GE', 'en', 'Georgia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DE', 'en', 'Germany');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GH', 'en', 'Ghana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GI', 'en', 'Gibraltar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GR', 'en', 'Greece');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GL', 'en', 'Greenland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GD', 'en', 'Grenada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GP', 'en', 'Guadeloupe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GU', 'en', 'Guam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GT', 'en', 'Guatemala');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GG', 'en', 'Guernsey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GN', 'en', 'Guinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GW', 'en', 'Guinea-Bissau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GY', 'en', 'Guyana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HT', 'en', 'Haiti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HM', 'en', 'Heard Island and McDonald Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HN', 'en', 'Honduras');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HK', 'en', 'Hong Kong SAR China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HU', 'en', 'Hungary');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IS', 'en', 'Iceland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IN', 'en', 'India');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ID', 'en', 'Indonesia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IR', 'en', 'Iran');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IQ', 'en', 'Iraq');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IE', 'en', 'Ireland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IM', 'en', 'Isle of Man');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IL', 'en', 'Israel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IT', 'en', 'Italy');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JM', 'en', 'Jamaica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JP', 'en', 'Japan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JE', 'en', 'Jersey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JT', 'en', 'Johnston Island');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JO', 'en', 'Jordan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KZ', 'en', 'Kazakhstan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KE', 'en', 'Kenya');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KI', 'en', 'Kiribati');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KW', 'en', 'Kuwait');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KG', 'en', 'Kyrgyzstan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LA', 'en', 'Laos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LV', 'en', 'Latvia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LB', 'en', 'Lebanon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LS', 'en', 'Lesotho');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LR', 'en', 'Liberia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LY', 'en', 'Libya');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LI', 'en', 'Liechtenstein');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LT', 'en', 'Lithuania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LU', 'en', 'Luxembourg');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MO', 'en', 'Macau SAR China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MK', 'en', 'Macedonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MG', 'en', 'Madagascar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MW', 'en', 'Malawi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MY', 'en', 'Malaysia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MV', 'en', 'Maldives');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ML', 'en', 'Mali');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MT', 'en', 'Malta');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MH', 'en', 'Marshall Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MQ', 'en', 'Martinique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MR', 'en', 'Mauritania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MU', 'en', 'Mauritius');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YT', 'en', 'Mayotte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FX', 'en', 'Metropolitan France');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MX', 'en', 'Mexico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FM', 'en', 'Micronesia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MI', 'en', 'Midway Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MD', 'en', 'Moldova');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MC', 'en', 'Monaco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MN', 'en', 'Mongolia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ME', 'en', 'Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MS', 'en', 'Montserrat');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MA', 'en', 'Morocco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MZ', 'en', 'Mozambique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MM', 'en', 'Myanmar [Burma]');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NA', 'en', 'Namibia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NR', 'en', 'Nauru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NP', 'en', 'Nepal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NL', 'en', 'Netherlands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AN', 'en', 'Netherlands Antilles');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NT', 'en', 'Neutral Zone');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NC', 'en', 'New Caledonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NZ', 'en', 'New Zealand');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NI', 'en', 'Nicaragua');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NE', 'en', 'Niger');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NG', 'en', 'Nigeria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NU', 'en', 'Niue');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NF', 'en', 'Norfolk Island');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KP', 'en', 'North Korea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VD', 'en', 'North Vietnam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MP', 'en', 'Northern Mariana Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NO', 'en', 'Norway');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('OM', 'en', 'Oman');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PC', 'en', 'Pacific Islands Trust Territory');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PK', 'en', 'Pakistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PW', 'en', 'Palau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PS', 'en', 'Palestinian Territories');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PA', 'en', 'Panama');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PZ', 'en', 'Panama Canal Zone');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PG', 'en', 'Papua New Guinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PY', 'en', 'Paraguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YD', 'en', `People's Democratic Republic of Yemen`);
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PE', 'en', 'Peru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PH', 'en', 'Philippines');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PN', 'en', 'Pitcairn Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PL', 'en', 'Poland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PT', 'en', 'Portugal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PR', 'en', 'Puerto Rico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('QA', 'en', 'Qatar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RO', 'en', 'Romania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RU', 'en', 'Russia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RW', 'en', 'Rwanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RE', 'en', 'Réunion');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BL', 'en', 'Saint Barthélemy');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SH', 'en', 'Saint Helena');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KN', 'en', 'Saint Kitts and Nevis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LC', 'en', 'Saint Lucia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MF', 'en', 'Saint Martin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PM', 'en', 'Saint Pierre and Miquelon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VC', 'en', 'Saint Vincent and the Grenadines');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WS', 'en', 'Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SM', 'en', 'San Marino');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SA', 'en', 'Saudi Arabia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SN', 'en', 'Senegal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RS', 'en', 'Serbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CS', 'en', 'Serbia and Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SC', 'en', 'Seychelles');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SL', 'en', 'Sierra Leone');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SG', 'en', 'Singapore');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SK', 'en', 'Slovakia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SI', 'en', 'Slovenia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SB', 'en', 'Solomon Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SO', 'en', 'Somalia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZA', 'en', 'South Africa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GS', 'en', 'South Georgia and the South Sandwich Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KR', 'en', 'South Korea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ES', 'en', 'Spain');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LK', 'en', 'Sri Lanka');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SD', 'en', 'Sudan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SR', 'en', 'Suriname');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SJ', 'en', 'Svalbard and Jan Mayen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SZ', 'en', 'Swaziland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SE', 'en', 'Sweden');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CH', 'en', 'Switzerland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SY', 'en', 'Syria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ST', 'en', 'São Tomé and Príncipe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TW', 'en', 'Taiwan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TJ', 'en', 'Tajikistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TZ', 'en', 'Tanzania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TH', 'en', 'Thailand');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TL', 'en', 'Timor-Leste');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TG', 'en', 'Togo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TK', 'en', 'Tokelau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TO', 'en', 'Tonga');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TT', 'en', 'Trinidad and Tobago');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TN', 'en', 'Tunisia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TR', 'en', 'Turkey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TM', 'en', 'Turkmenistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TC', 'en', 'Turks and Caicos Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TV', 'en', 'Tuvalu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UM', 'en', 'U.S. Minor Outlying Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PU', 'en', 'U.S. Miscellaneous Pacific Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VI', 'en', 'U.S. Virgin Islands');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UG', 'en', 'Uganda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UA', 'en', 'Ukraine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SU', 'en', 'Union of Soviet Socialist Republics');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AE', 'en', 'United Arab Emirates');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GB', 'en', 'United Kingdom');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('US', 'en', 'United States');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZZ', 'en', 'Unknown or Invalid Region');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UY', 'en', 'Uruguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UZ', 'en', 'Uzbekistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VU', 'en', 'Vanuatu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VA', 'en', 'Vatican City');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VE', 'en', 'Venezuela');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VN', 'en', 'Vietnam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WK', 'en', 'Wake Island');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WF', 'en', 'Wallis and Futuna');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EH', 'en', 'Western Sahara');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YE', 'en', 'Yemen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZM', 'en', 'Zambia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZW', 'en', 'Zimbabwe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AX', 'en', 'Åland Islands');
