
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AF', 'es', 'Afganistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AL', 'es', 'Albania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DE', 'es', 'Alemania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AD', 'es', 'Andorra');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AO', 'es', 'Angola');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AI', 'es', 'Anguila');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AG', 'es', 'Antigua y Barbuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AN', 'es', 'Antillas Neerlandesas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AQ', 'es', 'Antártida');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SA', 'es', 'Arabia Saudí');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DZ', 'es', 'Argelia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AR', 'es', 'Argentina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AM', 'es', 'Armenia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AW', 'es', 'Aruba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AU', 'es', 'Australia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AT', 'es', 'Austria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AZ', 'es', 'Azerbaiyán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BS', 'es', 'Bahamas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BH', 'es', 'Bahréin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BD', 'es', 'Bangladesh');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BB', 'es', 'Barbados');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BZ', 'es', 'Belice');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BJ', 'es', 'Benín');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BM', 'es', 'Bermudas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BY', 'es', 'Bielorrusia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BO', 'es', 'Bolivia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BA', 'es', 'Bosnia-Herzegovina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BW', 'es', 'Botsuana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BR', 'es', 'Brasil');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BN', 'es', 'Brunéi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BG', 'es', 'Bulgaria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BF', 'es', 'Burkina Faso');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BI', 'es', 'Burundi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BT', 'es', 'Bután');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BE', 'es', 'Bélgica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CV', 'es', 'Cabo Verde');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KH', 'es', 'Camboya');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CM', 'es', 'Camerún');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CA', 'es', 'Canadá');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TD', 'es', 'Chad');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CL', 'es', 'Chile');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CN', 'es', 'China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CY', 'es', 'Chipre');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VA', 'es', 'Ciudad del Vaticano');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CO', 'es', 'Colombia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KM', 'es', 'Comoras');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CG', 'es', 'Congo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KP', 'es', 'Corea del Norte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KR', 'es', 'Corea del Sur');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CR', 'es', 'Costa Rica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CI', 'es', 'Costa de Marfil');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HR', 'es', 'Croacia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CU', 'es', 'Cuba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DK', 'es', 'Dinamarca');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DM', 'es', 'Dominica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EC', 'es', 'Ecuador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EG', 'es', 'Egipto');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SV', 'es', 'El Salvador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AE', 'es', 'Emiratos Árabes Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ER', 'es', 'Eritrea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SK', 'es', 'Eslovaquia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SI', 'es', 'Eslovenia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ES', 'es', 'España');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('US', 'es', 'Estados Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EE', 'es', 'Estonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ET', 'es', 'Etiopía');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PH', 'es', 'Filipinas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FI', 'es', 'Finlandia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FJ', 'es', 'Fiyi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FR', 'es', 'Francia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GA', 'es', 'Gabón');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GM', 'es', 'Gambia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GE', 'es', 'Georgia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GH', 'es', 'Ghana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GI', 'es', 'Gibraltar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GD', 'es', 'Granada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GR', 'es', 'Grecia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GL', 'es', 'Groenlandia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GP', 'es', 'Guadalupe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GU', 'es', 'Guam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GT', 'es', 'Guatemala');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GF', 'es', 'Guayana Francesa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GG', 'es', 'Guernsey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GN', 'es', 'Guinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GQ', 'es', 'Guinea Ecuatorial');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GW', 'es', 'Guinea-Bissau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GY', 'es', 'Guyana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HT', 'es', 'Haití');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HN', 'es', 'Honduras');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HU', 'es', 'Hungría');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IN', 'es', 'India');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ID', 'es', 'Indonesia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IQ', 'es', 'Iraq');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IE', 'es', 'Irlanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IR', 'es', 'Irán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BV', 'es', 'Isla Bouvet');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CX', 'es', 'Isla Christmas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NU', 'es', 'Isla Niue');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NF', 'es', 'Isla Norfolk');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IM', 'es', 'Isla de Man');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IS', 'es', 'Islandia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KY', 'es', 'Islas Caimán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CC', 'es', 'Islas Cocos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CK', 'es', 'Islas Cook');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FO', 'es', 'Islas Feroe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GS', 'es', 'Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HM', 'es', 'Islas Heard y McDonald');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FK', 'es', 'Islas Malvinas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MP', 'es', 'Islas Marianas del Norte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MH', 'es', 'Islas Marshall');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SB', 'es', 'Islas Salomón');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TC', 'es', 'Islas Turcas y Caicos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VG', 'es', 'Islas Vírgenes Británicas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VI', 'es', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UM', 'es', 'Islas menores alejadas de los Estados Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AX', 'es', 'Islas Åland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IL', 'es', 'Israel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IT', 'es', 'Italia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JM', 'es', 'Jamaica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JP', 'es', 'Japón');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JE', 'es', 'Jersey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JO', 'es', 'Jordania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KZ', 'es', 'Kazajistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KE', 'es', 'Kenia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KG', 'es', 'Kirguistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KI', 'es', 'Kiribati');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KW', 'es', 'Kuwait');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LA', 'es', 'Laos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LS', 'es', 'Lesoto');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LV', 'es', 'Letonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LR', 'es', 'Liberia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LY', 'es', 'Libia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LI', 'es', 'Liechtenstein');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LT', 'es', 'Lituania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LU', 'es', 'Luxemburgo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LB', 'es', 'Líbano');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MK', 'es', 'Macedonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MG', 'es', 'Madagascar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MY', 'es', 'Malasia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MW', 'es', 'Malaui');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MV', 'es', 'Maldivas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ML', 'es', 'Mali');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MT', 'es', 'Malta');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MA', 'es', 'Marruecos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MQ', 'es', 'Martinica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MU', 'es', 'Mauricio');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MR', 'es', 'Mauritania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YT', 'es', 'Mayotte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FM', 'es', 'Micronesia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MD', 'es', 'Moldavia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MN', 'es', 'Mongolia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ME', 'es', 'Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MS', 'es', 'Montserrat');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MZ', 'es', 'Mozambique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MM', 'es', 'Myanmar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MX', 'es', 'México');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MC', 'es', 'Mónaco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NA', 'es', 'Namibia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NR', 'es', 'Nauru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NP', 'es', 'Nepal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NI', 'es', 'Nicaragua');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NG', 'es', 'Nigeria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NO', 'es', 'Noruega');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NC', 'es', 'Nueva Caledonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NZ', 'es', 'Nueva Zelanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NE', 'es', 'Níger');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('OM', 'es', 'Omán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PK', 'es', 'Pakistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PW', 'es', 'Palau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PS', 'es', 'Palestina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PA', 'es', 'Panamá');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PG', 'es', 'Papúa Nueva Guinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PY', 'es', 'Paraguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NL', 'es', 'Países Bajos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PE', 'es', 'Perú');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PN', 'es', 'Pitcairn');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PF', 'es', 'Polinesia Francesa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PL', 'es', 'Polonia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PT', 'es', 'Portugal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PR', 'es', 'Puerto Rico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('QA', 'es', 'Qatar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HK', 'es', 'Región Administrativa Especial de Hong Kong de la República Popular China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MO', 'es', 'Región Administrativa Especial de Macao de la República Popular China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZZ', 'es', 'Región desconocida o no válida');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GB', 'es', 'Reino Unido');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CF', 'es', 'República Centroafricana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CZ', 'es', 'República Checa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CD', 'es', 'República Democrática del Congo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DO', 'es', 'República Dominicana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RE', 'es', 'Reunión');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RW', 'es', 'Ruanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RO', 'es', 'Rumanía');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RU', 'es', 'Rusia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WS', 'es', 'Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AS', 'es', 'Samoa Americana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BL', 'es', 'San Bartolomé');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KN', 'es', 'San Cristóbal y Nieves');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SM', 'es', 'San Marino');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MF', 'es', 'San Martín');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PM', 'es', 'San Pedro y Miquelón');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VC', 'es', 'San Vicente y las Granadinas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SH', 'es', 'Santa Elena');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LC', 'es', 'Santa Lucía');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ST', 'es', 'Santo Tomé y Príncipe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SN', 'es', 'Senegal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RS', 'es', 'Serbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CS', 'es', 'Serbia y Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SC', 'es', 'Seychelles');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SL', 'es', 'Sierra Leona');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SG', 'es', 'Singapur');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SY', 'es', 'Siria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SO', 'es', 'Somalia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LK', 'es', 'Sri Lanka');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SZ', 'es', 'Suazilandia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZA', 'es', 'Sudáfrica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SD', 'es', 'Sudán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SE', 'es', 'Suecia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CH', 'es', 'Suiza');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SR', 'es', 'Surinam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SJ', 'es', 'Svalbard y Jan Mayen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EH', 'es', 'Sáhara Occidental');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TH', 'es', 'Tailandia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TW', 'es', 'Taiwán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TZ', 'es', 'Tanzania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TJ', 'es', 'Tayikistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IO', 'es', 'Territorio Británico del Océano Índico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TF', 'es', 'Territorios Australes Franceses');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TL', 'es', 'Timor Oriental');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TG', 'es', 'Togo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TK', 'es', 'Tokelau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TO', 'es', 'Tonga');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TT', 'es', 'Trinidad y Tobago');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TM', 'es', 'Turkmenistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TR', 'es', 'Turquía');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TV', 'es', 'Tuvalu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TN', 'es', 'Túnez');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UA', 'es', 'Ucrania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UG', 'es', 'Uganda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UY', 'es', 'Uruguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UZ', 'es', 'Uzbekistán');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VU', 'es', 'Vanuatu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VE', 'es', 'Venezuela');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VN', 'es', 'Vietnam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WF', 'es', 'Wallis y Futuna');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YE', 'es', 'Yemen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DJ', 'es', 'Yibuti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZM', 'es', 'Zambia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZW', 'es', 'Zimbabue');
