
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AF', 'fr', 'Afghanistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZA', 'fr', 'Afrique du Sud');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AL', 'fr', 'Albanie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DZ', 'fr', 'Algérie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DE', 'fr', 'Allemagne');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AD', 'fr', 'Andorre');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AO', 'fr', 'Angola');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AI', 'fr', 'Anguilla');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AQ', 'fr', 'Antarctique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AG', 'fr', 'Antigua-et-Barbuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AN', 'fr', 'Antilles néerlandaises');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SA', 'fr', 'Arabie saoudite');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AR', 'fr', 'Argentine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AM', 'fr', 'Arménie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AW', 'fr', 'Aruba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AU', 'fr', 'Australie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AT', 'fr', 'Autriche');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AZ', 'fr', 'Azerbaïdjan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BS', 'fr', 'Bahamas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BH', 'fr', 'Bahreïn');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BD', 'fr', 'Bangladesh');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BB', 'fr', 'Barbade');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BE', 'fr', 'Belgique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BZ', 'fr', 'Belize');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BM', 'fr', 'Bermudes');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BT', 'fr', 'Bhoutan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BO', 'fr', 'Bolivie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BA', 'fr', 'Bosnie-Herzégovine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BW', 'fr', 'Botswana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BN', 'fr', 'Brunéi Darussalam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BR', 'fr', 'Brésil');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BG', 'fr', 'Bulgarie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BF', 'fr', 'Burkina Faso');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BI', 'fr', 'Burundi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BY', 'fr', 'Bélarus');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BJ', 'fr', 'Bénin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KH', 'fr', 'Cambodge');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CM', 'fr', 'Cameroun');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CA', 'fr', 'Canada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CV', 'fr', 'Cap-Vert');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CL', 'fr', 'Chili');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CN', 'fr', 'Chine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CY', 'fr', 'Chypre');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CO', 'fr', 'Colombie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KM', 'fr', 'Comores');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CG', 'fr', 'Congo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KP', 'fr', 'Corée du Nord');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KR', 'fr', 'Corée du Sud');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CR', 'fr', 'Costa Rica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HR', 'fr', 'Croatie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CU', 'fr', 'Cuba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CI', 'fr', 'Côte d’Ivoire');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DK', 'fr', 'Danemark');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DJ', 'fr', 'Djibouti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DM', 'fr', 'Dominique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SV', 'fr', 'El Salvador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ES', 'fr', 'Espagne');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EE', 'fr', 'Estonie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FJ', 'fr', 'Fidji');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FI', 'fr', 'Finlande');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FR', 'fr', 'France');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GA', 'fr', 'Gabon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GM', 'fr', 'Gambie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GH', 'fr', 'Ghana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GI', 'fr', 'Gibraltar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GD', 'fr', 'Grenade');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GL', 'fr', 'Groenland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GR', 'fr', 'Grèce');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GP', 'fr', 'Guadeloupe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GU', 'fr', 'Guam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GT', 'fr', 'Guatemala');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GG', 'fr', 'Guernesey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GN', 'fr', 'Guinée');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GQ', 'fr', 'Guinée équatoriale');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GW', 'fr', 'Guinée-Bissau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GY', 'fr', 'Guyana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GF', 'fr', 'Guyane française');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GE', 'fr', 'Géorgie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GS', 'fr', 'Géorgie du Sud et les îles Sandwich du Sud');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HT', 'fr', 'Haïti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HN', 'fr', 'Honduras');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HU', 'fr', 'Hongrie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IN', 'fr', 'Inde');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ID', 'fr', 'Indonésie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IQ', 'fr', 'Irak');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IR', 'fr', 'Iran');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IE', 'fr', 'Irlande');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IS', 'fr', 'Islande');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IL', 'fr', 'Israël');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IT', 'fr', 'Italie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JM', 'fr', 'Jamaïque');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JP', 'fr', 'Japon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JE', 'fr', 'Jersey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JO', 'fr', 'Jordanie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KZ', 'fr', 'Kazakhstan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KE', 'fr', 'Kenya');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KG', 'fr', 'Kirghizistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KI', 'fr', 'Kiribati');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KW', 'fr', 'Koweït');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LA', 'fr', 'Laos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LS', 'fr', 'Lesotho');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LV', 'fr', 'Lettonie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LB', 'fr', 'Liban');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LY', 'fr', 'Libye');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LR', 'fr', 'Libéria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LI', 'fr', 'Liechtenstein');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LT', 'fr', 'Lituanie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LU', 'fr', 'Luxembourg');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MK', 'fr', 'Macédoine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MG', 'fr', 'Madagascar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MY', 'fr', 'Malaisie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MW', 'fr', 'Malawi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MV', 'fr', 'Maldives');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ML', 'fr', 'Mali');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MT', 'fr', 'Malte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MA', 'fr', 'Maroc');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MQ', 'fr', 'Martinique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MU', 'fr', 'Maurice');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MR', 'fr', 'Mauritanie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YT', 'fr', 'Mayotte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MX', 'fr', 'Mexique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MD', 'fr', 'Moldavie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MC', 'fr', 'Monaco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MN', 'fr', 'Mongolie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MS', 'fr', 'Montserrat');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ME', 'fr', 'Monténégro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MZ', 'fr', 'Mozambique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MM', 'fr', 'Myanmar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NA', 'fr', 'Namibie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NR', 'fr', 'Nauru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NI', 'fr', 'Nicaragua');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NE', 'fr', 'Niger');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NG', 'fr', 'Nigéria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NU', 'fr', 'Niue');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NO', 'fr', 'Norvège');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NC', 'fr', 'Nouvelle-Calédonie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NZ', 'fr', 'Nouvelle-Zélande');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NP', 'fr', 'Népal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('OM', 'fr', 'Oman');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UG', 'fr', 'Ouganda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UZ', 'fr', 'Ouzbékistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PK', 'fr', 'Pakistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PW', 'fr', 'Palaos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PA', 'fr', 'Panama');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PG', 'fr', 'Papouasie-Nouvelle-Guinée');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PY', 'fr', 'Paraguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NL', 'fr', 'Pays-Bas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PH', 'fr', 'Philippines');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PN', 'fr', 'Pitcairn');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PL', 'fr', 'Pologne');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PF', 'fr', 'Polynésie française');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PR', 'fr', 'Porto Rico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PT', 'fr', 'Portugal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PE', 'fr', 'Pérou');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('QA', 'fr', 'Qatar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HK', 'fr', 'R.A.S. chinoise de Hong Kong');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MO', 'fr', 'R.A.S. chinoise de Macao');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RO', 'fr', 'Roumanie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GB', 'fr', 'Royaume-Uni');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RU', 'fr', 'Russie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RW', 'fr', 'Rwanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CF', 'fr', 'République centrafricaine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DO', 'fr', 'République dominicaine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CD', 'fr', 'République démocratique du Congo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CZ', 'fr', 'République tchèque');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RE', 'fr', 'Réunion');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EH', 'fr', 'Sahara occidental');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BL', 'fr', 'Saint-Barthélémy');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KN', 'fr', 'Saint-Kitts-et-Nevis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SM', 'fr', 'Saint-Marin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MF', 'fr', 'Saint-Martin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PM', 'fr', 'Saint-Pierre-et-Miquelon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VC', 'fr', 'Saint-Vincent-et-les Grenadines');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SH', 'fr', 'Sainte-Hélène');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LC', 'fr', 'Sainte-Lucie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WS', 'fr', 'Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AS', 'fr', 'Samoa américaines');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ST', 'fr', 'Sao Tomé-et-Principe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RS', 'fr', 'Serbie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CS', 'fr', 'Serbie-et-Monténégro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SC', 'fr', 'Seychelles');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SL', 'fr', 'Sierra Leone');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SG', 'fr', 'Singapour');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SK', 'fr', 'Slovaquie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SI', 'fr', 'Slovénie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SO', 'fr', 'Somalie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SD', 'fr', 'Soudan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LK', 'fr', 'Sri Lanka');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CH', 'fr', 'Suisse');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SR', 'fr', 'Suriname');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SE', 'fr', 'Suède');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SJ', 'fr', 'Svalbard et Île Jan Mayen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SZ', 'fr', 'Swaziland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SY', 'fr', 'Syrie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SN', 'fr', 'Sénégal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TJ', 'fr', 'Tadjikistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TZ', 'fr', 'Tanzanie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TW', 'fr', 'Taïwan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TD', 'fr', 'Tchad');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TF', 'fr', 'Terres australes françaises');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IO', 'fr', `Territoire britannique de l'océan Indien`);
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PS', 'fr', 'Territoire palestinien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TH', 'fr', 'Thaïlande');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TL', 'fr', 'Timor oriental');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TG', 'fr', 'Togo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TK', 'fr', 'Tokelau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TO', 'fr', 'Tonga');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TT', 'fr', 'Trinité-et-Tobago');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TN', 'fr', 'Tunisie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TM', 'fr', 'Turkménistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TR', 'fr', 'Turquie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TV', 'fr', 'Tuvalu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UA', 'fr', 'Ukraine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UY', 'fr', 'Uruguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VU', 'fr', 'Vanuatu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VE', 'fr', 'Venezuela');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VN', 'fr', 'Viêt Nam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WF', 'fr', 'Wallis-et-Futuna');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YE', 'fr', 'Yémen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZM', 'fr', 'Zambie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZW', 'fr', 'Zimbabwe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZZ', 'fr', 'région indéterminée');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EG', 'fr', 'Égypte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AE', 'fr', 'Émirats arabes unis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EC', 'fr', 'Équateur');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ER', 'fr', 'Érythrée');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VA', 'fr', 'État de la Cité du Vatican');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FM', 'fr', 'États fédérés de Micronésie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('US', 'fr', 'États-Unis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ET', 'fr', 'Éthiopie');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BV', 'fr', 'Île Bouvet');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CX', 'fr', 'Île Christmas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NF', 'fr', 'Île Norfolk');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IM', 'fr', 'Île de Man');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KY', 'fr', 'Îles Caïmans');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CC', 'fr', 'Îles Cocos - Keeling');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CK', 'fr', 'Îles Cook');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FO', 'fr', 'Îles Féroé');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HM', 'fr', 'Îles Heard et MacDonald');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FK', 'fr', 'Îles Malouines');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MP', 'fr', 'Îles Mariannes du Nord');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MH', 'fr', 'Îles Marshall');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UM', 'fr', 'Îles Mineures Éloignées des États-Unis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SB', 'fr', 'Îles Salomon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TC', 'fr', 'Îles Turks et Caïques');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VG', 'fr', 'Îles Vierges britanniques');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VI', 'fr', 'Îles Vierges des États-Unis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AX', 'fr', 'Îles Åland');
