
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AF', 'de', 'Afghanistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AX', 'de', 'Alandinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AL', 'de', 'Albanien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DZ', 'de', 'Algerien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UM', 'de', 'Amerikanisch-Ozeanien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AS', 'de', 'Amerikanisch-Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VI', 'de', 'Amerikanische Jungferninseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AD', 'de', 'Andorra');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AO', 'de', 'Angola');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AI', 'de', 'Anguilla');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AQ', 'de', 'Antarktis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AG', 'de', 'Antigua und Barbuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AR', 'de', 'Argentinien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AM', 'de', 'Armenien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AW', 'de', 'Aruba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AZ', 'de', 'Aserbaidschan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AU', 'de', 'Australien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BS', 'de', 'Bahamas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BH', 'de', 'Bahrain');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BD', 'de', 'Bangladesch');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BB', 'de', 'Barbados');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BY', 'de', 'Belarus');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BE', 'de', 'Belgien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BZ', 'de', 'Belize');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BJ', 'de', 'Benin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BM', 'de', 'Bermuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BT', 'de', 'Bhutan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BO', 'de', 'Bolivien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BA', 'de', 'Bosnien und Herzegowina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BW', 'de', 'Botsuana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BV', 'de', 'Bouvetinsel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BR', 'de', 'Brasilien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VG', 'de', 'Britische Jungferninseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IO', 'de', 'Britisches Territorium im Indischen Ozean');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BN', 'de', 'Brunei Darussalam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BG', 'de', 'Bulgarien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BF', 'de', 'Burkina Faso');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BI', 'de', 'Burundi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CL', 'de', 'Chile');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CN', 'de', 'China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CK', 'de', 'Cookinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CR', 'de', 'Costa Rica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CI', 'de', 'Côte d’Ivoire');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CD', 'de', 'Demokratische Republik Kongo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KP', 'de', 'Demokratische Volksrepublik Korea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DE', 'de', 'Deutschland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DM', 'de', 'Dominica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DO', 'de', 'Dominikanische Republik');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DJ', 'de', 'Dschibuti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DK', 'de', 'Dänemark');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EC', 'de', 'Ecuador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SV', 'de', 'El Salvador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ER', 'de', 'Eritrea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EE', 'de', 'Estland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FK', 'de', 'Falklandinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FJ', 'de', 'Fidschi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FI', 'de', 'Finnland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FR', 'de', 'Frankreich');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GF', 'de', 'Französisch-Guayana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PF', 'de', 'Französisch-Polynesien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TF', 'de', 'Französische Süd- und Antarktisgebiete');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FO', 'de', 'Färöer');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GA', 'de', 'Gabun');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GM', 'de', 'Gambia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GE', 'de', 'Georgien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GH', 'de', 'Ghana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GI', 'de', 'Gibraltar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GD', 'de', 'Grenada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GR', 'de', 'Griechenland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GL', 'de', 'Grönland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GP', 'de', 'Guadeloupe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GU', 'de', 'Guam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GT', 'de', 'Guatemala');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GG', 'de', 'Guernsey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GN', 'de', 'Guinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GW', 'de', 'Guinea-Bissau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GY', 'de', 'Guyana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HT', 'de', 'Haiti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HM', 'de', 'Heard- und McDonald-Inseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HN', 'de', 'Honduras');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IN', 'de', 'Indien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ID', 'de', 'Indonesien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IQ', 'de', 'Irak');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IR', 'de', 'Iran');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IE', 'de', 'Irland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IS', 'de', 'Island');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IM', 'de', 'Isle of Man');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IL', 'de', 'Israel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IT', 'de', 'Italien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JM', 'de', 'Jamaika');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JP', 'de', 'Japan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YE', 'de', 'Jemen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JE', 'de', 'Jersey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JO', 'de', 'Jordanien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KY', 'de', 'Kaimaninseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KH', 'de', 'Kambodscha');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CM', 'de', 'Kamerun');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CA', 'de', 'Kanada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CV', 'de', 'Kap Verde');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KZ', 'de', 'Kasachstan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('QA', 'de', 'Katar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KE', 'de', 'Kenia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KG', 'de', 'Kirgisistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KI', 'de', 'Kiribati');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CC', 'de', 'Kokosinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CO', 'de', 'Kolumbien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KM', 'de', 'Komoren');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CG', 'de', 'Kongo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HR', 'de', 'Kroatien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CU', 'de', 'Kuba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KW', 'de', 'Kuwait');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LA', 'de', 'Laos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LS', 'de', 'Lesotho');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LV', 'de', 'Lettland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LB', 'de', 'Libanon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LR', 'de', 'Liberia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LY', 'de', 'Libyen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LI', 'de', 'Liechtenstein');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LT', 'de', 'Litauen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LU', 'de', 'Luxemburg');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MG', 'de', 'Madagaskar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MW', 'de', 'Malawi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MY', 'de', 'Malaysia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MV', 'de', 'Malediven');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ML', 'de', 'Mali');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MT', 'de', 'Malta');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MA', 'de', 'Marokko');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MH', 'de', 'Marshallinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MQ', 'de', 'Martinique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MR', 'de', 'Mauretanien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MU', 'de', 'Mauritius');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YT', 'de', 'Mayotte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MK', 'de', 'Mazedonien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MX', 'de', 'Mexiko');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FM', 'de', 'Mikronesien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MC', 'de', 'Monaco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MN', 'de', 'Mongolei');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ME', 'de', 'Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MS', 'de', 'Montserrat');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MZ', 'de', 'Mosambik');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MM', 'de', 'Myanmar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NA', 'de', 'Namibia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NR', 'de', 'Nauru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NP', 'de', 'Nepal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NC', 'de', 'Neukaledonien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NZ', 'de', 'Neuseeland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NI', 'de', 'Nicaragua');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NL', 'de', 'Niederlande');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AN', 'de', 'Niederländische Antillen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NE', 'de', 'Niger');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NG', 'de', 'Nigeria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NU', 'de', 'Niue');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NF', 'de', 'Norfolkinsel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NO', 'de', 'Norwegen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MP', 'de', 'Nördliche Marianen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('OM', 'de', 'Oman');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TL', 'de', 'Osttimor');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PK', 'de', 'Pakistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PW', 'de', 'Palau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PS', 'de', 'Palästinensische Gebiete');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PA', 'de', 'Panama');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PG', 'de', 'Papua-Neuguinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PY', 'de', 'Paraguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PE', 'de', 'Peru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PH', 'de', 'Philippinen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PN', 'de', 'Pitcairn');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PL', 'de', 'Polen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PT', 'de', 'Portugal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PR', 'de', 'Puerto Rico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KR', 'de', 'Republik Korea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MD', 'de', 'Republik Moldau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RW', 'de', 'Ruanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RO', 'de', 'Rumänien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RU', 'de', 'Russische Föderation');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RE', 'de', 'Réunion');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SB', 'de', 'Salomonen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZM', 'de', 'Sambia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WS', 'de', 'Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SM', 'de', 'San Marino');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SA', 'de', 'Saudi-Arabien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SE', 'de', 'Schweden');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CH', 'de', 'Schweiz');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SN', 'de', 'Senegal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RS', 'de', 'Serbien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CS', 'de', 'Serbien und Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SC', 'de', 'Seychellen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SL', 'de', 'Sierra Leone');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZW', 'de', 'Simbabwe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SG', 'de', 'Singapur');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SK', 'de', 'Slowakei');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SI', 'de', 'Slowenien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SO', 'de', 'Somalia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HK', 'de', 'Sonderverwaltungszone Hongkong');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MO', 'de', 'Sonderverwaltungszone Macao');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ES', 'de', 'Spanien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LK', 'de', 'Sri Lanka');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BL', 'de', 'St. Barthélemy');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SH', 'de', 'St. Helena');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KN', 'de', 'St. Kitts und Nevis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LC', 'de', 'St. Lucia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MF', 'de', 'St. Martin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PM', 'de', 'St. Pierre und Miquelon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VC', 'de', 'St. Vincent und die Grenadinen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SD', 'de', 'Sudan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SR', 'de', 'Suriname');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SJ', 'de', 'Svalbard und Jan Mayen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SZ', 'de', 'Swasiland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SY', 'de', 'Syrien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ST', 'de', 'São Tomé und Príncipe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZA', 'de', 'Südafrika');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GS', 'de', 'Südgeorgien und die Südlichen Sandwichinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TJ', 'de', 'Tadschikistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TW', 'de', 'Taiwan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TZ', 'de', 'Tansania');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TH', 'de', 'Thailand');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TG', 'de', 'Togo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TK', 'de', 'Tokelau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TO', 'de', 'Tonga');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TT', 'de', 'Trinidad und Tobago');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TD', 'de', 'Tschad');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CZ', 'de', 'Tschechische Republik');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TN', 'de', 'Tunesien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TM', 'de', 'Turkmenistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TC', 'de', 'Turks- und Caicosinseln');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TV', 'de', 'Tuvalu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TR', 'de', 'Türkei');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UG', 'de', 'Uganda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UA', 'de', 'Ukraine');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZZ', 'de', 'Unbekannte oder ungültige Region');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HU', 'de', 'Ungarn');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UY', 'de', 'Uruguay');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UZ', 'de', 'Usbekistan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VU', 'de', 'Vanuatu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VA', 'de', 'Vatikanstadt');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VE', 'de', 'Venezuela');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AE', 'de', 'Vereinigte Arabische Emirate');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('US', 'de', 'Vereinigte Staaten');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GB', 'de', 'Vereinigtes Königreich');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VN', 'de', 'Vietnam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WF', 'de', 'Wallis und Futuna');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CX', 'de', 'Weihnachtsinsel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EH', 'de', 'Westsahara');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CF', 'de', 'Zentralafrikanische Republik');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CY', 'de', 'Zypern');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EG', 'de', 'Ägypten');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GQ', 'de', 'Äquatorialguinea');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ET', 'de', 'Äthiopien');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AT', 'de', 'Österreich');
