
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AF', 'pt', 'Afeganistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AL', 'pt', 'Albânia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DE', 'pt', 'Alemanha');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AD', 'pt', 'Andorra');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AO', 'pt', 'Angola');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AI', 'pt', 'Anguilla');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AN', 'pt', 'Antilhas Holandesas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AQ', 'pt', 'Antártida');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AG', 'pt', 'Antígua e Barbuda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AR', 'pt', 'Argentina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DZ', 'pt', 'Argélia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AM', 'pt', 'Armênia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AW', 'pt', 'Aruba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SA', 'pt', 'Arábia Saudita');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AU', 'pt', 'Austrália');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AZ', 'pt', 'Azerbaijão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BS', 'pt', 'Bahamas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BH', 'pt', 'Bahrain');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BD', 'pt', 'Bangladesh');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BB', 'pt', 'Barbados');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BY', 'pt', 'Belarus');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BZ', 'pt', 'Belize');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BJ', 'pt', 'Benin');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BM', 'pt', 'Bermudas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BO', 'pt', 'Bolívia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BW', 'pt', 'Botsuana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BR', 'pt', 'Brasil');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BN', 'pt', 'Brunei');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BG', 'pt', 'Bulgária');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BF', 'pt', 'Burquina Faso');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BI', 'pt', 'Burundi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BT', 'pt', 'Butão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BE', 'pt', 'Bélgica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BA', 'pt', 'Bósnia-Herzegovina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CV', 'pt', 'Cabo Verde');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KH', 'pt', 'Camboja');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CA', 'pt', 'Canadá');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KZ', 'pt', 'Casaquistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('QA', 'pt', 'Catar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TD', 'pt', 'Chade');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CL', 'pt', 'Chile');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CN', 'pt', 'China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CY', 'pt', 'Chipre');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SG', 'pt', 'Cingapura');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CO', 'pt', 'Colômbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KM', 'pt', 'Comores');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CG', 'pt', 'Congo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CD', 'pt', 'Congo-Kinshasa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KP', 'pt', 'Coreia do Norte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KR', 'pt', 'Coreia do Sul');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CR', 'pt', 'Costa Rica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CI', 'pt', 'Costa do Marfim');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HR', 'pt', 'Croácia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CU', 'pt', 'Cuba');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DK', 'pt', 'Dinamarca');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DJ', 'pt', 'Djibuti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DM', 'pt', 'Dominica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EG', 'pt', 'Egito');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SV', 'pt', 'El Salvador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AE', 'pt', 'Emirados Árabes Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EC', 'pt', 'Equador');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ER', 'pt', 'Eritreia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SK', 'pt', 'Eslováquia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SI', 'pt', 'Eslovênia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ES', 'pt', 'Espanha');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('US', 'pt', 'Estados Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EE', 'pt', 'Estônia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ET', 'pt', 'Etiópia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FJ', 'pt', 'Fiji');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PH', 'pt', 'Filipinas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FI', 'pt', 'Finlândia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FR', 'pt', 'França');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GA', 'pt', 'Gabão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GH', 'pt', 'Gana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GE', 'pt', 'Geórgia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GS', 'pt', 'Geórgia do Sul e Ilhas Sandwich do Sul');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GI', 'pt', 'Gibraltar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GD', 'pt', 'Granada');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GL', 'pt', 'Groênlandia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GR', 'pt', 'Grécia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GP', 'pt', 'Guadalupe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GU', 'pt', 'Guam');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GT', 'pt', 'Guatemala');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GG', 'pt', 'Guernsey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GY', 'pt', 'Guiana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GF', 'pt', 'Guiana Francesa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GN', 'pt', 'Guiné');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GW', 'pt', 'Guiné Bissau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GQ', 'pt', 'Guiné Equatorial');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GM', 'pt', 'Gâmbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HT', 'pt', 'Haiti');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NL', 'pt', 'Holanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HN', 'pt', 'Honduras');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HK', 'pt', 'Hong Kong, Região Admin. Especial da China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HU', 'pt', 'Hungria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BV', 'pt', 'Ilha Bouvet');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('HM', 'pt', 'Ilha Heard e Ilhas McDonald');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NF', 'pt', 'Ilha Norfolk');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IM', 'pt', 'Ilha de Man');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AX', 'pt', 'Ilhas Aland');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KY', 'pt', 'Ilhas Caiman');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CC', 'pt', 'Ilhas Coco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CK', 'pt', 'Ilhas Cook');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FO', 'pt', 'Ilhas Faroe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FK', 'pt', 'Ilhas Malvinas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MP', 'pt', 'Ilhas Marianas do Norte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MH', 'pt', 'Ilhas Marshall');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UM', 'pt', 'Ilhas Menores Distantes dos Estados Unidos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CX', 'pt', 'Ilhas Natal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SB', 'pt', 'Ilhas Salomão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TC', 'pt', 'Ilhas Turks e Caicos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VG', 'pt', 'Ilhas Virgens Britânicas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VI', 'pt', 'Ilhas Virgens dos EUA');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ID', 'pt', 'Indonésia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IQ', 'pt', 'Iraque');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IE', 'pt', 'Irlanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IR', 'pt', 'Irã');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IS', 'pt', 'Islândia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IL', 'pt', 'Israel');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IT', 'pt', 'Itália');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YE', 'pt', 'Iêmen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JM', 'pt', 'Jamaica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JP', 'pt', 'Japão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JE', 'pt', 'Jersey');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('JO', 'pt', 'Jordânia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KW', 'pt', 'Kuwait');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LS', 'pt', 'Lesoto');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LV', 'pt', 'Letônia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LR', 'pt', 'Libéria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LI', 'pt', 'Liechtenstein');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LT', 'pt', 'Lituânia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LU', 'pt', 'Luxemburgo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LB', 'pt', 'Líbano');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LY', 'pt', 'Líbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MO', 'pt', 'Macau, Região Admin. Especial da China');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MK', 'pt', 'Macedônia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MG', 'pt', 'Madagascar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MW', 'pt', 'Malawi');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MV', 'pt', 'Maldivas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ML', 'pt', 'Mali');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MT', 'pt', 'Malta');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MY', 'pt', 'Malásia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MA', 'pt', 'Marrocos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MQ', 'pt', 'Martinica');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MR', 'pt', 'Mauritânia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MU', 'pt', 'Maurício');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('YT', 'pt', 'Mayotte');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MM', 'pt', 'Mianmar');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('FM', 'pt', 'Micronésia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MD', 'pt', 'Moldávia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MN', 'pt', 'Mongólia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ME', 'pt', 'Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MS', 'pt', 'Montserrat');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MZ', 'pt', 'Moçambique');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MX', 'pt', 'México');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MC', 'pt', 'Mônaco');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NA', 'pt', 'Namíbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NR', 'pt', 'Nauru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NP', 'pt', 'Nepal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NI', 'pt', 'Nicarágua');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NG', 'pt', 'Nigéria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NU', 'pt', 'Niue');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NO', 'pt', 'Noruega');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NC', 'pt', 'Nova Caledônia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NZ', 'pt', 'Nova Zelândia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('NE', 'pt', 'Níger');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('OM', 'pt', 'Omã');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PW', 'pt', 'Palau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PA', 'pt', 'Panamá');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PG', 'pt', 'Papua-Nova Guiné');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PK', 'pt', 'Paquistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PY', 'pt', 'Paraguai');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PE', 'pt', 'Peru');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PN', 'pt', 'Pitcairn');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PF', 'pt', 'Polinésia Francesa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PL', 'pt', 'Polônia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PR', 'pt', 'Porto Rico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PT', 'pt', 'Portugal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KG', 'pt', 'Quirguistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KI', 'pt', 'Quiribati');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KE', 'pt', 'Quênia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZZ', 'pt', 'Região desconhecida ou inválida');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('GB', 'pt', 'Reino Unido');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CF', 'pt', 'República Centro-Africana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('DO', 'pt', 'República Dominicana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LA', 'pt', 'República Popular Democrática do Laos');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CZ', 'pt', 'República Tcheca');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CM', 'pt', 'República dos Camarões');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RE', 'pt', 'Reunião');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RO', 'pt', 'Romênia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RW', 'pt', 'Ruanda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RU', 'pt', 'Rússia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('EH', 'pt', 'Saara Ocidental');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PM', 'pt', 'Saint Pierre e Miquelon');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WS', 'pt', 'Samoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AS', 'pt', 'Samoa Americana');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SM', 'pt', 'San Marino');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SH', 'pt', 'Santa Helena');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LC', 'pt', 'Santa Lúcia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SN', 'pt', 'Senegal');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SL', 'pt', 'Serra Leoa');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SC', 'pt', 'Seychelles');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SO', 'pt', 'Somália');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('LK', 'pt', 'Sri Lanka');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SZ', 'pt', 'Suazilândia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SD', 'pt', 'Sudão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SR', 'pt', 'Suriname');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SE', 'pt', 'Suécia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CH', 'pt', 'Suíça');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SJ', 'pt', 'Svalbard e Jan Mayen');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('BL', 'pt', 'São Bartolomeu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('KN', 'pt', 'São Cristovão e Nevis');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('MF', 'pt', 'São Martinho');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ST', 'pt', 'São Tomé e Príncipe');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VC', 'pt', 'São Vicente e Granadinas');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('RS', 'pt', 'Sérvia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('CS', 'pt', 'Sérvia e Montenegro');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('SY', 'pt', 'Síria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TJ', 'pt', 'Tadjiquistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TH', 'pt', 'Tailândia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TW', 'pt', 'Taiwan');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TZ', 'pt', 'Tanzânia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IO', 'pt', 'Território Britânico do Oceano Índico');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('PS', 'pt', 'Território da Palestina');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TF', 'pt', 'Territórios Franceses do Sul');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TL', 'pt', 'Timor Leste');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TG', 'pt', 'Togo');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TK', 'pt', 'Tokelau');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TO', 'pt', 'Tonga');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TT', 'pt', 'Trinidad e Tobago');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TN', 'pt', 'Tunísia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TM', 'pt', 'Turcomenistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TR', 'pt', 'Turquia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('TV', 'pt', 'Tuvalu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UA', 'pt', 'Ucrânia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UG', 'pt', 'Uganda');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UY', 'pt', 'Uruguai');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('UZ', 'pt', 'Uzbequistão');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VU', 'pt', 'Vanuatu');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VA', 'pt', 'Vaticano');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VE', 'pt', 'Venezuela');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('VN', 'pt', 'Vietnã');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('WF', 'pt', 'Wallis e Futuna');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZW', 'pt', 'Zimbábue');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZM', 'pt', 'Zâmbia');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('ZA', 'pt', 'África do Sul');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('AT', 'pt', 'Áustria');
INSERT INTO `countries_localized` (`country_code`, `locale_id`, `name`) VALUES ('IN', 'pt', 'Índia');
